ER図
nyacos/lovepdca pull request #5
Opened 2023-08-30 14:53 UTC by nyacos

https://gyazo.com/10a1eedf9b514f026c0c0f05ac3e3fec

2023-08-31 03:21 UTC, Tsuchiya2 commented
ご提出ありがとうございます。
以下コメントになります。

---

■共通
・各テーブル、各カラムの説明をお願いします。
・カラムに型の情報も加えてください。例：string

■usersテーブル
・uaer_name：`@user.user_name`となってしまうのでnameカラムの方が直感的で良さそうです。
・line_infomation：LINEログインを実装する際にどんなカラム・どんな型が必要か調べてみましょう。

■categoriesテーブル
・category_name：nameの方が良さそうです。
・tasksテーブルとcategoriesテーブルが多対多のリレーションになっていますが、確認の上、適切な形に修正しましょう。

■task_statusesテーブル
・tasksテーブルと1対1のリレーションになっていますが、適切か確認もしくは説明をお願いしたいです。
・user_idもあることから、tasksテーブルとusersテーブルの中間テーブルかと推測しましたが違いますでしょうか。

■recommendsテーブル
・テーブル名は複数形にしましょう。
・カラムからuserテーブルとactionsテーブルを繋ぐ中間テーブルかと推測しましたが、その際リレーションは適切なものになっているか確認をお願いします。

■commentsテーブル
・commentカラム：body等の方が良いかと思いました。（理由：`@comment.comment`と呼び出すのは直感的ではないかと思ったためです）

■chatsテーブル
・各cchatにタイトルとかは不要な感じでしょうか？
・user_id：chatを作ったユーザーのIDでしょうか？それともchatに参加しているユーザーのIDでしょうか？

■messagesテーブル
・messageカラム：textなど、他のカラム名にしましょう。
・avaterカラム：usersテーブルではないかと思ったのですがいかがでしょうか？

2023-08-31 07:48 UTC, nyacos commented
ご確認いただきありがとうございます。

- ■共通
    
    ・各テーブル、各カラムの説明をお願いします。
    
    ・カラムに型の情報も加えてください。例：string
    

### Users

- name:ユーザー名
- avater: アイコン
- line_user_id: LINEのユーザーID
- role: 管理者ユーザーか一般ユーザーかを判別する

### Tasks

PLAN,DO,CHECKのチェックリストが入るテーブルです

- content: チェックリストの内容
- category_id: カテゴリーID

### Categories

- name: PLAN,DO,CHECKのいずれかが入る

### Task_statuses

- status: チェックが入っているかいないかを管理するカラム

### Actions

Action＝ユーザーからの相談が入るテーブルです。

- avater: 相談しているユーザーのアイコン
- title: 相談のタイトル
- body: 相談の本文

### Comments

Actionに対するコメントが入るテーブルです。

- avater: コメントするユーザーのアイコン
- body: コメント

### Recommends

ユーザーへの相談やコメントと似たActionのレコメンドが入るテーブルです。

### Chats/Messages

チャットの相手とチャットのメッセージを入れるテーブルです。

- titile: チャットのタイトル
- avater: 発言するユーザーのアイコン
- message: メッセージの本文

型の情報を追記しました。
https://gyazo.com/ce657a0e952c85abcab5c253dcfd5c9c
![ce657a0e952c85abcab5c253dcfd5c9c](https://github.com/nyacos/lovepdca/assets/121137970/a6b5b952-699a-429d-9fab-5e3b4cdcde4c)


- ■usersテーブル
    
    ・uaer_name：`@user.user_name`となってしまうのでnameカラムの方が直感的で良さそうです。
    
    ・line_infomation：LINEログインを実装する際にどんなカラム・どんな型が必要か調べてみましょう。
    

user.nameへ修正しました。

LINEログインを実装する際にはline_user_idが必要だったため、修正しました。

- ■categoriesテーブル
    
    ・category_name：nameの方が良さそうです。
    
    ・tasksテーブルとcategoriesテーブルが多対多のリレーションになっていますが、確認の上、適切な形に修正しましょう。
    

category.nameへ修正しました。

1つのcategoryに対してtaskは複数あるので1対多に修正しました。

- ■task_statusesテーブル
    
    ・tasksテーブルと1対1のリレーションになっていますが、適切か確認もしくは説明をお願いしたいです。
    
    ・user_idもあることから、tasksテーブルとusersテーブルの中間テーブルかと推測しましたが違いますでしょうか。
    

1つのtaskに対して複数のユーザーのstatusを管理したいため、1対多に修正しました。task_statusesテーブルはtasksテーブルとusersテーブルの中間テーブルです。

- ■recommendsテーブル
    
    ・テーブル名は複数形にしましょう。
    
    ・カラムからuserテーブルとactionsテーブルを繋ぐ中間テーブルかと推測しましたが、その際リレーションは適切なものになっているか確認をお願いします。
    

テーブル名を複数形に修正しました。

RecommendsとActionsが1対1になっていましたが、1つのActionを複数のユーザーへレコメンドする場合あるため1対多に修正しました。

- ■commentsテーブル
    
    ・commentカラム：body等の方が良いかと思いました。（理由：`@comment.comment`と呼び出すのは直感的ではないかと思ったためです）
    

comment.bodyへ修正しました。

- ■chatsテーブル
    
    ・各cchatにタイトルとかは不要な感じでしょうか？
    
    ・user_id：chatを作ったユーザーのIDでしょうか？それともchatに参加しているユーザーのIDでしょうか？
    

各チャットへタイトルがあった方がユーザーも認識しやすいと思うため、titileを追加しました。

chatを作ったユーザーのIDで考えています。

- ■messagesテーブル
    
    ・messageカラム：textなど、他のカラム名にしましょう。
    
    ・avaterカラム：usersテーブルではないかと思ったのですがいかがでしょうか？
    

message.textへ修正しました。

user.avaterを表示するため、FKを追記しました。

2023-09-01 02:15 UTC, Tsuchiya2 commented
ご対応ありがとうございます。

---

■確認依頼箇所
・複数のテーブルにavatorカラムが存在していますが、comments時もaction時もmessage時もusersテーブル内のavatorを使用すればよいかと思うのですがいかがでしょうか？

2023-09-01 03:01 UTC, nyacos commented
https://gyazo.com/ad7cb2f41620223b08beb09430018950
![ad7cb2f41620223b08beb09430018950](https://github.com/nyacos/lovepdca/assets/121137970/57c87c8f-ee4e-46e9-aa41-3963e197178c)

ご確認いただきありがとうございます。
少し勘違いしていました。user.avatorを使用すれば良いため、他のテーブルのavatorを削除しました。

2023-09-01 12:53 UTC, tarakish requested changes
修正確認しました。
すでにご回答済みの部分があれば申し訳ございませんが、以下コメントです。

---
- Task
  - こちらは管理者側で作成されたものを全ユーザー共通で使うイメージでしょうか？ユーザーが作るものではないかを確認したいです。

- Task_statuses
  - こちら中間テーブルであればリレーションの矢印が不足しているので修正をお願いします！

2023-09-02 00:18 UTC, nyacos commented
> 修正確認しました。 すでにご回答済みの部分があれば申し訳ございませんが、以下コメントです。
> 
> * Task
>   
>   * こちらは管理者側で作成されたものを全ユーザー共通で使うイメージでしょうか？ユーザーが作るものではないかを確認したいです。
> * Task_statuses
>   
>   * こちら中間テーブルであればリレーションの矢印が不足しているので修正をお願いします！

Taskテーブルは管理者側が作成したものを全ユーザー共通で使うイメージです。

Task_statusesのリレーションの矢印を追加しました。

https://gyazo.com/7708a97b0d634863031555ac8603da54
<img width="810" alt="7708a97b0d634863031555ac8603da54" src="https://github.com/nyacos/lovepdca/assets/121137970/9f8c65c2-c79d-4cf9-a2d0-70fa4034ff23">

2023-09-03 07:20 UTC, nyacos commented
ご確認いただきありがとうございます！

2023-09-03 07:20 UTC, merged